name: Build test

on:
  push:
    branches:
      - '**'        # matches every branch
      - '!main'     # excludes main
      - '!dev-nightly'     # excludes nightly

  pull_request:
    branches: [ "main", "dev-nightly" ]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ['7.0.x']

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version:  ${{ matrix.dotnet-version }}
    
    - name: Initialise submodules
      run: git submodule update --init

    - name: Restore dependencies
      run: dotnet restore

    - name: Restore nuget packages
      run: nuget restore

    - name: Build
      run: .\build.cmd

    - name: Upload server
      uses: actions/upload-artifact@v3
      with:
        name: RageCoop.Server
        path: bin/Release/Server

    - name: Upload Client
      uses: actions/upload-artifact@v3
      with:
        name: RageCoop.Client
        path: bin/Release/Client

    - uses: actions/checkout@v2
      
