name: Nightly-build

on:
  push:
    branches: [ "dev-nightly" ]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x']

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version:  ${{ matrix.dotnet-version }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Restore nuget packages
      run: nuget restore

    - name: Build artifacts
      run: .\build.cmd

    - name: Build server for different platforms
      run: .\publish-server.cmd

    - uses: vimtor/action-zip@v1
      with:
        files: bin/Release/Client
        dest: RageCoop.Client.zip

    - uses: vimtor/action-zip@v1
      with:
        files: bin/API
        dest: bin/Artifacts/SDK.zip

    - uses: vimtor/action-zip@v1
      with:
        files: bin/Release/Server/win-x64
        dest: bin/Artifacts/RageCoop.Server-win-x64.zip

    - uses: vimtor/action-zip@v1
      with:
        files: bin/Release/Server/win-x86
        dest: bin/Artifacts/RageCoop.Server-win-x86.zip

    - uses: vimtor/action-zip@v1
      with:
        files: bin/Release/Server/linux-x64
        dest: bin/Artifacts/RageCoop.Server-linux-x64.zip

    - uses: vimtor/action-zip@v1
      with:
        files: bin/Release/Server/linux-arm
        dest: bin/Artifacts/RageCoop.Server-linux-arm.zip

    - uses: vimtor/action-zip@v1
      with:
        files: bin/Release/Server/linux-arm
        dest: bin/Artifacts/RageCoop.Server-linux-arm.zip

    - uses: vimtor/action-zip@v1
      with:
        files: bin/Release/Server/linux-arm64
        dest: bin/Artifacts/RageCoop.Server-linux-arm64.zip

    - name: Deploy binaries 
      uses: Sardelka9515/deploy-nightly@v0.7
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # automatically provided by github actions
      with:
        upload_url: https://uploads.github.com/repos/RAGECOOP/GTAV-RESOURCES/releases/75463254/assets{?name,label}
        release_id: 75463254 
        asset_path: bin/Artifacts
        asset_content_type: application/zip
        max_releases: 7

    - uses: actions/checkout@v2
      
